export const equipmentOptions = [
  { label: "Auto Carrier", value: "AC" },
  { label: "B-Train", value: "BT" },
  { label: "Conestoga", value: "CN" },
  { label: "Container", value: "C" },
  { label: "Container Insulated", value: "CI" },
  { label: "Container Refrigerated", value: "CR" },
  { label: "Conveyor", value: "CV" },
  { label: "Double Drop", value: "DD" },
  { label: "Drop Deck Landoll", value: "LA" },
  { label: "Dump Trailer", value: "DT" },
  { label: "Flatbed", value: "F" },
  { label: "Flatbed Air-Ride", value: "FA" },
  { label: "Flatbed Conestoga", value: "FN" },
  { label: "Flatbed Double", value: "F2" },
  { label: "Flatbed HazMat", value: "FZ" },
  { label: "Flatbed Hotshot", value: "FH" },
  { label: "Flatbed Maxi", value: "MX" },
  { label: "Flatbed or Step Deck", value: "FD" },
  { label: "Flatbed Over dimension", value: "FO" },
  { label: "Flatbed w/Chains", value: "FC" },
  { label: "Flatbed w/Sides", value: "FS" },
  { label: "Flatbed w/Tarps", value: "FT" },
  { label: "Flatbed w/Team", value: "FM" },
  { label: "Flatbed/Van/Reefer", value: "FR" },
  { label: "Hopper Bottom", value: "HB" },
  { label: "Insulated Van or Reefer", value: "IR" },
  { label: "Lowboy", value: "LB" },
  { label: "Lowboy or Rem Gooseneck (RGN)", value: "LR" },
  { label: "Lowboy Over dimension", value: "LO" },
  { label: "Moving Van", value: "MV" },
  { label: "Power Only", value: "PO" },
  { label: "Only Load Out", value: "PL" },
  { label: "Power Only Tow Away", value: "PT" },
  { label: "Reefer", value: "R" },
  { label: "Pneumatic", value: "NU" },
  { label: "Reefer Air-Ride", value: "RA" },
  { label: "Reefer Double", value: "R2" },
  { label: "Reefer HazMat", value: "RZ" },
  { label: "Reefer Intermodal", value: "RN" },
  { label: "Reefer Logistics", value: "RL" },
  { label: "Reefer or Vented Van", value: "RV" },
  { label: "Reefer Pallet Exchange", value: "RP" },
  { label: "Reefer w/Team", value: "RM" },
  { label: "Removable Gooseneck", value: "RG" },
  { label: "Sprinter Van", value: "SV" },
  { label: "Sprinter Van HazMat", value: "SZ" },
  { label: "Sprinter Van Temp-Controlled", value: "SC" },
  { label: "Sprinter Van w/Team", value: "SM" },
  { label: "Step Deck", value: "SD" },
  { label: "Step Deck or Rem Gooseneck (RGN)", value: "SR" },
  { label: "Stepdeck Conestoga", value: "SN" },
  { label: "Straight Box Truck", value: "SB" },
  { label: "Straight Box Truck HazMat", value: "BZ" },
  { label: "Straight Box Truck Reefer", value: "BR" },
  { label: "Stretch Trailer", value: "ST" },
  { label: "Tanker Aluminum", value: "TA" },
  { label: "Tanker Intermodal", value: "TN" },
  { label: "Tanker Steel", value: "TS" },
  { label: "Truck and Trailer", value: "TT" },
  { label: "Van", value: "V" },
  { label: "Van Air-Ride", value: "VA" },
  { label: "Van Blanket Wrap", value: "VW" },
  { label: "Van Conestoga", value: "VS" },
  { label: "Van Double", value: "V2" },
  { label: "Van HazMat", value: "VZ" },
  { label: "Van Hotshot", value: "VH" },
  { label: "Van Insulated", value: "VI" },
  { label: "Van Intermodal", value: "VN" },
  { label: "Van Lift-Gate", value: "VG" },
  { label: "Van Logistics", value: "VL" },
  { label: "Van Open-Top", value: "OT" },
  { label: "Van or Flatbed", value: "VF" },
  { label: "Van or Flatbed w/Tarps", value: "VT" },
  { label: "Van or Reefer", value: "VR" },
  { label: "Van Pallet Exchange", value: "VP" },
  { label: "Van Roller Bed", value: "VB" },
  { label: "Van Triple", value: "V3" },
  { label: "Van Vented", value: "VV" },
  { label: "Van w/Curtains", value: "VC" },
  { label: "Van w/Team", value: "VM" }
];
