const EQUIPMENT_TYPES = [
  { code: "AC", desc: "Auto Carrier" },
  { code: "BT", desc: "B-Train" },
  { code: "CN", desc: "Conestoga" },
  { code: "C", desc: "Container" },
  { code: "CI", desc: "Container Insulated" },
  { code: "CR", desc: "Container Refrigerated" },
  { code: "CV", desc: "Conveyor" },
  { code: "DD", desc: "Double Drop" },
  { code: "LA", desc: "Drop Deck Landoll" },
  { code: "DT", desc: "Dump Trailer" },
  { code: "F", desc: "Flatbed" },
  { code: "FA", desc: "Flatbed Air-Ride" },
  { code: "FN", desc: "Flatbed Conestoga" },
  { code: "F2", desc: "Flatbed Double" },
  { code: "FZ", desc: "Flatbed HazMat" },
  { code: "FH", desc: "Flatbed Hotshot" },
  { code: "MX", desc: "Flatbed Maxi" },
  { code: "FD", desc: "Flatbed or Step Deck" },
  { code: "FO", desc: "Flatbed Over dimension" },
  { code: "FC", desc: "Flatbed w/Chains" },
  { code: "FS", desc: "Flatbed w/Sides" },
  { code: "FT", desc: "Flatbed w/Tarps" },
  { code: "FM", desc: "Flatbed w/Team" },
  { code: "FR", desc: "Flatbed/Van/Reefer" },
  { code: "HB", desc: "Hopper Bottom" },
  { code: "IR", desc: "Insulated Van or Reefer" },
  { code: "LB", desc: "Lowboy" },
  { code: "LR", desc: "Lowboy or Rem Gooseneck (RGN)" },
  { code: "LO", desc: "Lowboy Over dimension" },
  { code: "MV", desc: "Moving Van" },
  { code: "PO", desc: "Power Only" },
  { code: "PL", desc: "Only Load Out" },
  { code: "PT", desc: "Power Only Tow Away" },
  { code: "R", desc: "Reefer" },
  { code: "NU", desc: "Pneumatic" },
  { code: "RA", desc: "Reefer Air-Ride" },
  { code: "R2", desc: "Reefer Double" },
  { code: "RZ", desc: "Reefer HazMat" },
  { code: "RN", desc: "Reefer Intermodal" },
  { code: "RL", desc: "Reefer Logistics" },
  { code: "RV", desc: "Reefer or Vented Van" },
  { code: "RP", desc: "Reefer Pallet Exchange" },
  { code: "RM", desc: "Reefer w/Team" },
  { code: "RG", desc: "Removable Gooseneck" },
  { code: "SV", desc: "Sprinter Van" },
  { code: "SZ", desc: "Sprinter Van HazMat" },
  { code: "SC", desc: "Sprinter Van Temp-Controlled" },
  { code: "SM", desc: "Sprinter Van w/Team" },
  { code: "SD", desc: "Step Deck" },
  { code: "SR", desc: "Step Deck or Rem Gooseneck (RGN)" },
  { code: "SN", desc: "Stepdeck Conestoga" },
  { code: "SB", desc: "Straight Box Truck" },
  { code: "BZ", desc: "Straight Box Truck HazMat" },
  { code: "BR", desc: "Straight Box Truck Reefer" },
  { code: "ST", desc: "Stretch Trailer" },
  { code: "TA", desc: "Tanker Aluminum" },
  { code: "TN", desc: "Tanker Intermodal" },
  { code: "TS", desc: "Tanker Steel" },
  { code: "TT", desc: "Truck and Trailer" },
  { code: "V", desc: "Van" },
  { code: "VA", desc: "Van Air-Ride" },
  { code: "VW", desc: "Van Blanket Wrap" },
  { code: "VS", desc: "Van Conestoga" },
  { code: "V2", desc: "Van Double" },
  { code: "VZ", desc: "Van HazMat" },
  { code: "VH", desc: "Van Hotshot" },
  { code: "VI", desc: "Van Insulated" },
  { code: "VN", desc: "Van Intermodal" },
  { code: "VG", desc: "Van Lift-Gate" },
  { code: "VL", desc: "Van Logistics" },
  { code: "OT", desc: "Van Open-Top" },
  { code: "VF", desc: "Van or Flatbed" },
  { code: "VT", desc: "Van or Flatbed w/Tarps" },
  { code: "VR", desc: "Van or Reefer" },
  { code: "VP", desc: "Van Pallet Exchange" },
  { code: "VB", desc: "Van Roller Bed" },
  { code: "V3", desc: "Van Triple" },
  { code: "VV", desc: "Van Vented" },
  { code: "VC", desc: "Van w/Curtains" },
  { code: "VM", desc: "Van w/Team" }
];

export default EQUIPMENT_TYPES;
